### PR TITLE
LPS-54176 Clear mail session

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
test

**Comment by cgoncas** [comment]
test

**Comment by cgoncas** [comment]
test

**Comment by cgoncas** [comment]
test

**Comment by cgoncas** [comment]
test

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/101. [See changes here.](https://github.com/mdelapenya/liferay-portal/compare/bae3313~2...bae3313) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
