### PR TITLE
LPS-55878 Use the interface WhenIsIndexable when this behaviour can be tested (override the isIndexableBaseModel behaviour)

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/3469. [See changes here.](https://github.com/mdelapenya/liferay-portal/compare/41ead98~1...41ead98) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
