### PR TITLE
LPS-55878 These test are already tested in every original update Basemodel test case.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/3516. [See changes here.](https://github.com/mdelapenya/liferay-portal/compare/aadcb89~1...aadcb89) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
