### PR TITLE
LPS-55761 Implement the new behaviour

### PR DESCRIPTION
**Pull request by cgoncas**
LPS-55761 Last refactor

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28242. [See changes here.](https://github.com/mdelapenya/liferay-portal/compare/899ea48~1...899ea48) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28251. [See changes here.](https://github.com/mdelapenya/liferay-portal/compare/bb5c888~1...bb5c888) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
