### PR TITLE
LPS-72844 tests configuration should not assume that MySQL database is case insensitive.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @mdelapenya,

I know that the pull request is recent but, could you review it tomorrow? we want to publish a new release and it's important to avoid this issue for CE users.

Muchas gracias Manu!

**Comment by sharonchoi** [comment]
Hey @mdelapenya,

Ditto Alberto's comment above, this pull affects the next fix pack, is it possible to send a backport in soon, as well? Thank you!

cc: @ZoltanTakacs

**Comment by mdelapenya** [comment]
LGTM 👍  I'd send it to Brian 😄 

image

**Comment by mdelapenya** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49344. [See changes here.](https://github.com/mdelapenya/liferay-portal/compare/c5f7ad6~1...c5f7ad6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
