### PR TITLE
LPS-44701 PortletURLImpl changes internal state during serialization when copying current render parameters

### PR DESCRIPTION
**Pull request by topolik**
https://issues.liferay.com/browse/LPS-44701

Hi @mdelapenya,

thanks for the old PR. I changed the fix because your fix would discard same values if set multiple times (?fib=1&fib=1&fib=2).

I think this is safer.

However, I didn't manage to run tests, which are crucial in this PR. So waiting for our CI :)

Thanks!

Now hopefully with correct semver :)

### CODE REVIEW

**Comment by topolik** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
@topolik test passes locally, let's wait for the CI and I'll send the PR to BChan

Thanks for the review!

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42047. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
