### PR TITLE
Gregory bretall lps 74573

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi Manuel, I am sending you this because Jonathan McCann is out of the office for today, if I should send this somewhere else please let me know.

Notes from Greg:

> I'm sending this through for Master although it's currently blocked from being tested on Master due to the inability to switch use Manual Configuration on the Asset Publisher. However, the affected code is identical between 7.0.x and Master and I've confirmed that this fixes the issue for 7.0.x.
> 
> This issue is very high priority for Hungary and they want it to get approved for an SDH. I'm also wondering if this can properly go through the reviews process if it isn't actually replicable on Master. Please let me know if there's any issues or anything I can do to help.

### CODE REVIEW

**Comment by mdelapenya** [comment]
Hey Sam, I'm not working for Core Infrastructure anymore. Please send your pull to Shuyang's team.

Thanks!

**Comment by SamZiemer** [comment]
Thanks, @mdelapenya, I have forwarded this to https://github.com/Preston-Crary/liferay-portal/pull/398

**Comment by mdelapenya** [comment]
stop:ci

**Comment by mdelapenya** [comment]
ci:stop

**Pull request closed without merging**
