### PR TITLE
pull-request-28280

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/28280

**Comment by mdelapenya** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/460. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/144. [See changes here.](https://github.com/mdelapenya/liferay-portal/compare/a156e4a~2...a156e4a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Hi @brianchandotcom, what do you mean by applying else where?

I've checked that storeFactory is called using renamed methods and now it seems consistent

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/461. [See changes here.](https://github.com/mdelapenya/liferay-portal/compare/04f97c6~3...04f97c6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28421. [See changes here.](https://github.com/mdelapenya/liferay-portal/compare/4afd67e~3...4afd67e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28497. [See changes here.](https://github.com/mdelapenya/liferay-portal/compare/07250d3~3...07250d3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
